---
- name: Initial setup of a raspbian system. Requires ssh enabled and pi in sudoers group.
  hosts: raspbian
  remote_user: pi
  become: yes
  
  tasks:
    - name: get up-to-date
      apt:
        update: yes
        upgrade: yes
        
    - name: Kernel update
      ansible.builtin.command: raspi-config update
      
    - name: Set locale
      ansible.builtin.command: kljdf



    - name: Install rpi-update
      apt:
        name: rpi-update
